### ISSUE TITLE
Usea Preprocessing Container Crashes

### ISSUE THREAD

**Issue by dfuchss** [SapienzaNLP/usea#3]
I'm currently trying to run usea locally.
Unfortunately, the preprocessing container crashes:

```
                               __  __   _____          ___

                              / / / /  / ___/  ___    /   |

                             / / / /   \__ \  / _ \  / /| |

                            / /_/ /   ___/ / /  __/ / ___ |

                            \____/   /____/  \___/ /_/  |_|


Universal Semantic Annotator: A Unified API for Multilingual WSD, SRL and AMR annotations


                                Preprocessing Module


Killed

                                 Sapienza NLP group


Downloading resources...


                               __  __   _____          ___

                              / / / /  / ___/  ___    /   |

                             / / / /   \__ \  / _ \  / /| |

                            / /_/ /   ___/ / /  __/ / ___ |

                            \____/   /____/  \___/ /_/  |_|


Universal Semantic Annotator: A Unified API for Multilingual WSD, SRL and AMR annotations


                                Preprocessing Module


                                 Sapienza NLP group


Downloading resources...
```

Do you have any idea how to fix this?

**Comment by Riccorl** [comment]
On which machine are you trying to run it? I'm asking because I'm facing the same issue on my local machine (M1 macOS), but not on Linux machines.

**Comment by dfuchss** [comment]
Currently, I'm running it on a Windows 11 machine.

Docker Information `docker info`:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.663GiB
 Name: docker-desktop
 ID: <redact>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by Riccorl** [comment]
Is it native or through WSL?

**Comment by Riccorl** [comment]
It seems like Docker is just slow in I/O operations, at least on my MacBook. Eventually it loads all the stuff. If you are using WSL, I think you have the same problem.

You can increase the timeout before it restarts, using the TIMEOUT environment variable. For example:

```bash
docker run --name usea-preprocessing -e TIMEOUT="1200" -p 22001:80 sapienzanlp/usea-preprocessing:1.0.0
```

I've updated the [Docker Hub page](https://hub.docker.com/r/sapienzanlp/usea-preprocessing), with additional documentation, listing the available environment variables.

**Comment by dfuchss** [comment]
Thanks for the information I'll check that. 
I'm running docker within the WSL which is quite fast since the (I think second) version of the wsl backend.

If this is the problem, you could also add that to the docker-compose file.

**Comment by Riccorl** [comment]
> Thanks for the information I'll check that.
> I'm running docker within the WSL which is quite fast since the (I think second) version of the wsl backend.

I'll check on WSL2 on my side too.

> If this is the problem, you could also add that to the docker-compose file.

I'll do asap, thanks!

**Comment by dfuchss** [comment]
I've tested it with the following compose file:

```yml
services:
  orchestrator:
    image: sapienzanlp/usea-service
    ports:
      - "${ORCHESTRATOR_PORT}:8000"
    restart: always
    depends_on:
      - "preprocessing"
      - "wsd"
      - "srl"
      - "amr"
    environment:
      PREPROCESSING_ENDPOINT: "${PREPROCESSING_ENDPOINT}"
      WSD_ENDPOINT: "${WSD_ENDPOINT}"
      SRL_ENDPOINT: "${SRL_ENDPOINT}"
      AMR_ENDPOINT: "${AMR_ENDPOINT}"

  preprocessing:
    image: sapienzanlp/usea-preprocessing:1.0.0
    restart: always
    environment:
      TIMEOUT: "12000"
    ports:
      - "${PREPROCESSING_PORT}:80"

  wsd:
    image: sapienzanlp/usea-wsd:1.0.0
    restart: always
    ports:
      - "${WSD_PORT}:80"

  srl:
    image: sapienzanlp/usea-srl:1.0.3-span
    restart: always
    ports:
      - "${SRL_PORT}:80"

  amr:
    image: sapienzanlp/usea-amr:1.0.1
    restart: always
    ports:
      - "${AMR_PORT}:80"

```

Nevertheless, the container still gets "killed". Do you have any other suggestions.

If the container downloads some models, I would suggest to add them directly to the image. Otherwise, any new container creates network load.
